---
defaults:
  notify:
    slack:
      channel: "#logs"
  timeout: 600s

stages:
  - name: test
    events: [push, CI]
  - name: build
    policies:
      - branch: ["|feature/*|", "dev", "master"]
        action: build

actions:
  - name: build
    commands:
      - go get github.com/tools/godep && go install github.com/tools/godep
      - make dep-restore
      - REV="$SG_HEAD" make build-image
      - docker login -e="." -u="$VAR_QUAY_USER" -p="$VAR_QUAY_AUTH" quay.io
      - REV="$SG_HEAD" BRANCH=$(echo "$SG_REF" | tr / _) make publish
    container: golang:1.4
    containerDir: /go/src/github.com/timelinelabs/romulus
